spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://actstudy.cq5wpqsqhs1s.us-west-2.rds.amazonaws.com:5432/actshop
    username: actshop
    password: qwertyui

